### ISSUE TITLE
no-script dark-theme is unreadable

### ISSUE THREAD

**Issue by Rudxain** [lavafroth/lavafroth.github.io#2]
- Firefox: ESR 128 & "for Android" 130
- Tested on 2 OSes with diff hardware, same bug
- uBO was used to disable JS
- Paradoxically, enabling Dark-Reader makes some text readable?

I'm willing to help fix this, but I'm **very** busy, and _even my own domain_ doesn't have [proper dark/light support](https://github.com/Rudxain/Rudxain.github.io/issues/10) 💀 (I hate Jekyll)

**Comment by lavafroth** [comment]
I'll look into how I can fix this in a couple days. Thank you for reporting this!
